AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'tmp/*'
    - 'Rakefile'
    - 'spec/*'
    - 'lib/sisimai/mta/userdefined.rb'

# Offense count: 14
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Enabled: false

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 144
  Exclude:
    - 'spec/*'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 512

Metrics/PerceivedComplexity:
  Enabled: false

Style/AsciiComments:
  Exclude:
    - 'lib/sisimai/mta/*.rb'
    - 'lib/sisimai/msp/ru/*.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - 'lib/sisimai/datetime.rb'
    - 'lib/sisimai/rfc5322.rb'
    - 'lib/sisimai/rhost.rb'
    - 'lib/sisimai/string.rb'
    - 'lib/sisimai/msp/*/*.rb'

Style/ClassVars:
  Enabled: false

Style/ConstantName:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Exclude:
    - 'lib/sisimai.rb'
    - 'lib/sisimai/mta.rb'
    - 'lib/sisimai/msp.rb'
    - 'lib/sisimai/mta/*'
    - 'lib/sisimai/msp/*/*'
    - 'lib/sisimai/rfc3463.rb'
    - 'lib/sisimai/rfc3834.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/ExtraSpacing:
  Enabled: false

# Configuration parameters: Exclude.
Style/FileName:
  Exclude:
    - 'spec/*_spec.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  EnforcedStyle: sprintf

Style/HashSyntax:
  Enabled: false

# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodName:
  Enabled: false

# Cop supports --auto-correct.
Style/NumericLiterals:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false
  PreferredDelimiters:
    '%r': '[]{}()||'
    '%w': '[]'

# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
Style/PredicateName:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
Style/RegexpLiteral:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  AllowIfMethodIsEmpty: true
  Exclude:
    - 'lib/sisimai.rb'
    - 'lib/sisimai/mta.rb'
    - 'lib/sisimai/msp.rb'
    - 'lib/sisimai/mta/*'
    - 'lib/sisimai/msp/*/*'
    - 'lib/sisimai/rfc3464.rb'
    - 'lib/sisimai/rfc3834.rb'
    - 'lib/sisimai/reason/*.rb'

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Exclude:
    - "spec/*"

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Enabled: false
  EnforcedStyleForMultiline: comma

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Enabled: false

# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Exclude:
    - 'spec/*'

