language: ruby
rvm:
  - 2.1.1
  - 2.2.2
  - 2.2.4
  - 2.3.0
  - jruby-9.0.0.0
  - jruby-9.0.4.0
before_install:
  - gem update bundler
script:
  - bundle exec rake spec
sudo: false
cache: bundler
notifications:
  recipients:
    - azumakuniyuki+travis-ci.org@gmail.com
  email:
    on_success: change
    on_failure: always

